SSC/Controllers/PropertyController.cs
using Microsoft.AspNetCore.Mvc;

namespace SSC.Controllers
{
    public class PropertyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SSC/Controllers/UnitOwnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SSC.Data;
using SSC.Models;

namespace SSC.Controllers
{
    public class UnitOwnersController : Controller
    {
        private readonly SscContext _context;

        public UnitOwnersController(SscContext context)
        {
            _context = context;
        }

        // GET: UnitOwners
        public async Task<IActionResult> Index()
        {
              return View(await _context.UnitOwners.ToListAsync());
        }

        // GET: UnitOwners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UnitOwners == null)
            {
                return NotFound();
            }

            var unitOwner = await _context.UnitOwners
                .FirstOrDefaultAsync(m => m.UnitNo == id);
            if (unitOwner == null)
            {
                return NotFound();
            }

            return View(unitOwner);
        }

        // GET: UnitOwners/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UnitOwners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UnitNo,OwnerName,ContactNo,Email,IsResidentInComplex")] UnitOwner unitOwner)
        {
            if (ModelState.IsValid)
            {
                _context.Add(unitOwner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            string errors = string.Join(";", ModelState.Values
                .SelectMany(x => x.Errors)
                .Select(x => x.ErrorMessage));

            ModelState.AddModelError("", errors);
            return View(unitOwner);
        }

        // GET: UnitOwners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UnitOwners == null)
            {
                return NotFound();
            }

            var unitOwner = await _context.UnitOwners.FindAsync(id);
            if (unitOwner == null)
            {
                return NotFound();
            }
            return View(unitOwner);
        }

        // POST: UnitOwners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UnitNo,OwnerName,ContactNo,Email,IsResidentInComplex")] UnitOwner unitOwner)
        {
            if (id != unitOwner.UnitNo)
            {
                return NotFound();

            }

            if (ModelState.IsValid)
            {
                try
                {
                    

                    _context.Update(unitOwner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UnitOwnerExists(unitOwner.UnitNo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(unitOwner);
        }

        // GET: UnitOwners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UnitOwners == null)
            {
                return NotFound();
            }

            var unitOwner = await _context.UnitOwners
                .FirstOrDefaultAsync(m => m.UnitNo == id);
            if (unitOwner == null)
            {
                return NotFound();
            }

            return View(unitOwner);
        }

        // POST: UnitOwners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UnitOwners == null)
            {
                return Problem("Entity set 'SscContext.UnitOwners'  is null.");
            }
            var unitOwner = await _context.UnitOwners.FindAsync(id);
            if (unitOwner != null)
            {
                _context.UnitOwners.Remove(unitOwner);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UnitOwnerExists(int id)
        {
          return _context.UnitOwners.Any(e => e.UnitNo == id);
        }
    }
}

SSC/Views/Property/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<style>
    #test1 {
        display: none;
    }

    #footer1 {
        display: none;
    }
</style>


<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SSC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SSC.styles.css" asp-append-version="true" />


    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Sunset clsoe Body Corporate Bootstrap Template - About</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: EstateAgency - v4.10.0
    * Template URL: https://bootstrapmade.com/real-estate-agency-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
    

    
</head>
<body>
   
  

    <!-- ======= Property Search Section ======= -->
    <div class="click-closed"></div>
    <!--/ Form Search Star /-->
    <!-- ======= Header/Navbar ======= -->
    <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SSC</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="UnitOwners" asp-action="Index">UnitOwners</a>
    </li>
    <li class="nav-item">
    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
    </ul>
    </div>
    </div>
    </nav>
    </header>
    <!--------------------------------------------->
    
    <!--------------------------------------------->



    <main id="main">

        <!-- ======= Intro Single ======= -->
        @*<section class="intro-single">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="title-single-box">
                            <h1 class="title-single">We Care for our people....</h1>
                        </div>
                    </div>
                    
                </div>
            </div>
        </section>*@<!-- End Intro Single-->
        <!-- ======= About Section ======= -->
        <section class="section-about" id="test2">
            <div class="container">
                <div class="row">                    
                    <div class="col-md-12 section-t8 position-relative">
                        <div class="row">
                            <div class="col-md-6 col-lg-5">
                                <img src="/img/SunsetClose.jpg" alt="" class="img-fluid">
                            </div>
                          
                            <div class="col-md-6 col-lg-5 section-md-t3">
                                <div class="title-box-d">
                                    <h3 class="title-d">
                                        Key Property Features
                                        <span class="color-d"></span> 
                                        <br>
                                    </h3>
                                </div>
                                <p class="color-text-a">

                                The Complex has ample visitors parking as well as a communal swimming pool area.
                                    <br />
                                The property is closest to Allandale on and off ramps and all its arterial roads, New Road and Olifantsfontein exits are easy to access from the property.
                                    <br />
                                Close to the Mall of Africa, Food Lovers Ridge Crest, Oliver Grove Centre Waterfall Corner, Kyalami Corner and other eminities.
                                </p>
                                <p class="color-text-a">
                                Sunset Close is a safe secured complex with access guard control and security. This Town house is tenanted and ideal for family living and rental returns.
                                    <br />



                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- =======Team Section ======= -->
        <!-- End About Section-->

    </main><!-- End #main -->


 
  <!-- Vendor JS Files -->
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="~/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="~/js/main.js"></script>


   
    

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
</body>
</html>